### PR TITLE
Update to action to build npm before package

### PR DESCRIPTION
**Pull request by dhric**

### CODE REVIEW

**Comment by tspence** [comment]
LGTM, but we'll also have to update the version number to 2022.4.35 to get it to build correctly.

**Comment by tspence** [comment]
As discussed, I think we should also add the external dependencies to rollup.config.js: ` 'external': ['axios', 'os', 'url']`

**Comment by tspence** [comment]
Thanks! One last edit - can you also edit package.json to update the version number to `2022.4.35`?

**Comment by dhric** [comment]
Version updated.

**Comment by tspence** [comment]
LGTM!  Ship it!

**Pull request merged**
